server:
  port: 8081

spring:
  kafka:
    bootstrap-servers:
      - localhost:9093
    consumer:
      group-id: kafka-examples-group
#      auto-offset-reset: earliest #default latest - whether to consume from the beginning of a topic partition or to only consume new messages when there is no initial offset for the consumer group
      properties:
        allow.auto.create.topics: false
    listener:
      missing-topics-fatal: true
      ack-mode: RECORD #default eh batch