server:
  port: 8082

spring:
  kafka:
    bootstrap-servers:
      - localhost:9093
      - localhost:29093
    consumer:
      group-id: group-x
      properties:
        allow.auto.create.topics: false
    listener:
      missing-topics-fatal: true
#      ack-mode: RECORD #default eh batch
#      concurrency: 2