server:
  port: 8081

spring:
  kafka:
    bootstrap-servers:
      - localhost:9093
      - localhost:29093
    producer:
      properties:
        request.timeout.ms: 5000 #default eh 30000
        delivery.timeout.ms: 5000 #default eh 120000 (e precisa ser maior ou igual que linger.ms + request.timeout.ms)