server:
  port: 8080

spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:29092
    consumer:
      group-id: group-1
      properties:
        allow.auto.create.topics: false
    listener:
      ack-mode: RECORD #default eh batch
#      concurrency: 2