version: "3"

networks:
  kafka-examples:
    driver: bridge

services:
  zookeeper-1:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper-1
    ports:
      - '2181:2181'
    networks:
      - kafka-examples
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    image: 'bitnami/kafka:latest'
    hostname: kafka-1
    ports:
      - '9092:9092'
      - '9093:9093'
      - '5556:5556'
    networks:
      - kafka-examples
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-1:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - JMX_PORT=5556
    depends_on:
      - zookeeper-1

  kafka-2:
    image: 'bitnami/kafka:latest'
    hostname: kafka-2
    ports:
      - '29092:9092'
      - '29093:9093'
      - '25556:5556'
    networks:
      - kafka-examples
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:29092,EXTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-2:29092,EXTERNAL://localhost:29093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - JMX_PORT=5556
    depends_on:
      - zookeeper-1

  kafka-manager:
    container_name: kafka-manager
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
    restart: always
    ports:
      - "9000:9000"
    networks:
      - kafka-examples
    environment:
      ZK_HOSTS: "zookeeper-1:2181"