version: "3"
services:
  zookeeper-1:
    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
    network_mode: host
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
    network_mode: host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-1

  kafka-2:
    image: 'bitnami/kafka:latest'
    #    ports:
    #      - '9092:9092'
    network_mode: host
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-1

  kafka-manager:
    container_name: kafka-manager
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
    restart: always
#    ports:
#      - "9000:9000"
    network_mode: host
    environment:
      ZK_HOSTS: "127.0.0.1:2181"

#  kafdrop:
#    image: obsidiandynamics/kafdrop:latest
#    networks:
#      - kafka-examples
#    depends_on:
#      - kafka-1
#    ports:
#      - "9000:9000"
#    environment:
#      KAFKA_BROKERCONNECT: kafka-1:9092

#networks:
#  kafka-examples:
#    driver: bridge